apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freqtrade-nfs-pvc
  namespace: jcrypt
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
