apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-freqtrade.homelinux.com
  namespace: jcrypt
spec:
  dnsNames:
    - freqtrade.homelinux.com
  secretName: secret-freqtrade.homelinux.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
